### ISSUE TITLE
Stretched menus/videos in Ultrawide?

### ISSUE THREAD

**Issue by Xbob42** [Banz99/Final-Fantasy-Type-0-Hd-Unlocker#13]
I figure this is to be expected, as adding in black bars for menus and FMVs is probably a crapton of work, but I figured I might as well ask. There's no way to fix these, right?

No biggie if not, the actual gameplay running at 3440 x 1440 @ 120 FPS is already awesome, just making sure I can't crank another knob up!

**Comment by Banz99** [comment]
I tried to improve the situation months ago but to no actual improvement. Given how little time I have to focus on this project nowadays, I'd rather focus on fixing the known high framerate problems when I can.

**Comment by Xbob42** [comment]
Understandable! I look forward to those being fixed when you're able!

**Comment by Banz99** [comment]
> Understandable! I look forward to those being fixed when you're able!

Hey pal, you might want to check out the test build that I sent in #17.

**Comment by Xbob42** [comment]
> > Understandable! I look forward to those being fixed when you're able!
> 
> Hey pal, you might want to check out the test build that I sent in #17.

Oh snap really? I'm on it!
