### ISSUE TITLE
Not working with 21:9 fix

### ISSUE THREAD

**Issue by BeauTaapken** [Banz99/Final-Fantasy-Type-0-Hd-Unlocker#3]
When i try to install this fix with the 21:9 edited exe, the game crashes after the config window. It would be great if it would be possible to be fixed for 21:9, either via your mod or working with the edited exe. This is the exe i'm using to make the game run at 3440x1440: [REMOVED]

**Comment by Banz99** [comment]
> When i try to install this fix with the 21:9 edited exe, the game crashes after the config window. It would be great if it would be possible to be fixed for 21:9, either via your mod or working with the edited exe. This is the exe i'm using to make the game run at 3440x1440: [fftype0hd.zip](https://github.com/Banz99/Final-Fantasy-Type-0-Hd-Unlocker/files/9534953/fftype0hd.zip)

I currently can't test It, but can you see if setting Resx and Resy to -1 in the .ini file fixes It?

**Comment by BeauTaapken** [comment]
unfortunately that didn't fix it, still doesn't start the real game after the config menu

**Comment by Banz99** [comment]
> unfortunately that didn't fix it, still doesn't start the real game after the config menu

After digging through every possible version of the exe that I could download from steam's depots, it's clear that it seems to match the first version of the game released on the platform ([SteamDb entry](https://steamdb.info/depot/340171/history/?changeid=M:710995259558354671)), however, it's a cracked exe from Codex (which I removed from this github issues tracker for obvious reasons) and there seems to be no tools available to let me decompile the changes just to isolate the 21:9 patch. Unless someone can find a proper patched exe, I can't really support this as I don't even know what breaks.

**Comment by BeauTaapken** [comment]
alright, thanks for clearing things up, wasn't aware it was a cracked exe. I guess i'll try looking for an updated 21:9 fix

**Comment by Banz99** [comment]
Seems like it was quite easier than I originally anticipated. Can you give this build a go before I push it to the repository?
[FFType0HDUnlocker_Ultrawide_Test.zip](https://github.com/Banz99/Final-Fantasy-Type-0-Hd-Unlocker/files/9548683/FFType0HDUnlocker_Ultrawide_Test.zip)

**Comment by BeauTaapken** [comment]
yes, it works now, entered my resolution in the ini file and fps also unlocks. Great work

**Comment by Banz99** [comment]
> yes, it works now, entered my resolution in the ini file and fps also unlocks. Great work

You may also want to give the fifth release with the custom FOV a go.
