### ISSUE TITLE
Game Doesn't Open

### ISSUE THREAD

**Issue by MythicAlys** [Banz99/Final-Fantasy-Type-0-Hd-Unlocker#9]
Just downloaded the game. I put this in the WIN folder, and tried to open it up. The launcher opens, I press start and.... Nothing. It just doesn't work.

I've tried removing it, the game works fine. Just doesn't work with this in.

**Comment by Banz99** [comment]
First of all, check that the .ini file (if you don't see any file extensions, it's the one with a config icon) is set to the correct resolution, then you might want to lower the game's antialiasing option as it is very expensive and memory consuming, and is known to cause the game to not load (see the readme on the big warning section). Other than that, I'm only supporting the latest version on Steam, any other one might or might not work and I don't really plan to look at it. In case all of the above has been checked, then please give me further details on your system.

**Comment by MythicAlys** [comment]
I'm a **_genius_** who managed to skip over the resolution bit on the GitHub despite reading over it multiple times
Fixed the resolution to my screen and it opens now, thank you!
